baseurl = "http://sagarayi.github.io" # Hostname (and path) to the root.
title = "sagarayi" # Site title.
theme = "hugo-coder" # Set the theme.
languagecode = "en" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[params] # theme parameters
    author = "Sagar Ayi" # Author's name.
    
    description = "Sagar Ayi's personal website" # Site description.
    info = "Mobile and Desktop application developer"
    keywords = "blog,developer,personal" # Site keywords.

    disqusShortname = "sagarayi" # Enable or disable Disqus

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
	custom_css = []

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    icon = "fab fa-github"
    url = "https://github.com/sagarayi/"
[[params.social]]
    name = "linkedIn"
    weight = 2
    icon = "fab fa-linkedin"
    url = "https://www.linkedin.com/in/sagarayi/"
[[params.social]]
    name = "Resume"
    weight = 1
    url = "https://drive.google.com/file/d/14eU4SDiiEhPDOclu845n0u302mtebItA/view?usp=sharing"    

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"